services:
  - type: web
    name: ease-apply
    env: docker
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
